#!/bin/bash -e
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Injecting apt repositories and packages ..."

DIR=/app

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive
if [ -f $DIR/apt-repositories ]; then
    cp "$DIR/apt-repositories" /etc/apt/sources.list.d/newrepos.list
fi
if [ -f $DIR/apt-debconf ]; then
    cat "$DIR/apt-debconf" | while read conf; do
        echo \$conf | debconf-set-selections
    done
fi
if [ -f $DIR/apt-packages ]; then
    PACKAGES=\$(cat "$DIR/apt-packages" | tr "\\n" " ")
    apt-get update
    apt-get install -y --force-yes \$PACKAGES
    echo "-----> Injected packages: \$PACKAGES"
fi
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
